WIP: Fix Rust-Analyzer artifact URL
eclipse/corrosion pull request #374
Opened 2021-05-31 18:21 UTC by rootkea

Closes #373

2021-05-31 18:23 UTC, rootkea commented
I have never programmed in Java so literally have no idea how to test this change I made.

Also shouldn't there be `".gz"` string appended at the end of URL?

2021-05-31 18:26 UTC, rootkea commented
And what about `rust-analyzer-x86_64-unknown-linux-musl.gz`? When to use that artifact?

2021-06-01 11:34 UTC, mickaelistria requested changes
Indeed, it seem s like .gz needs to be appended and an extra step added to gunzip the distribution. Do you think you can take care of this?

2021-06-01 11:34 UTC, mickaelistria commented on org.eclipse.corrosion/src/org/eclipse/corrosion/RustManager.java
> +								Platform.OS_MACOSX.equals(Platform.getOS()) ? "apple-darwin" : "os-not-found"); //$NON-NLS-1$ //$NON-NLS-2$
```suggestion
				(Platform.ARCH_AARCH64.equals(Platform.getOSArch()) ? "aarch64-" : //$NON-NLS-1$ //$NON-NLS-2$
						Platform.ARCH_X86_64.equals(Platform.getOSArch()) ? "x86_64-" : "arch-not-found") //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$
				+ (Platform.OS_LINUX.equals(Platform.getOS()) ? "unknown-linux-gnu" : //$NON-NLS-1$
						Platform.OS_WIN32.equals(Platform.getOS()) ? "pc-windows-msvc" : //$NON-NLS-1$
								Platform.OS_MACOSX.equals(Platform.getOS()) ? "apple-darwin" : "os-not-found"); //$NON-NLS-1$ //$NON-NLS-2$
```

2021-06-01 13:29 UTC, rootkea commented
Googlefoo says I gotta use `GZIPInputStream` but I'm afraid this will take more time as Java being unknown waters for me. So maybe you should go ahead and add the .gz decompress part. :)

2021-06-08 11:57 UTC, closed without merging